version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    volumes: 
      - jenkinsvolumes:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8080:8080
      - 50000:50000
volumes:
  jenkinsvolumes:
    external: true